DROP DATABASE IF EXISTS WEBDOC;

CREATE DATABASE WEBDOC;

USE DATABASE WEBDOC;

CREATE TABLE PHARMACY (
    PHARMID INT AUTO_INCREMENT PRIMARY KEY,
    PHARMNAME VARCHAR(50) NOT NULL,
    PHARMINVENTORY INT NOT NULL
);

CREATE TABLE CUSTOMER (
    CUSTOMID INT AUTO_INCREMENT PRIMARY KEY,
    CUSTOMNAME VARCHAR(50) NOT NULL,
    PASSWORD VARCHAR(50) NOT NULL
);

CREATE TABLE MEDICINE_INVENTORY (
    MEDICINEID INT AUTO_INCREMENT PRIMARY KEY,
    AMOUNT DECIMAL(13, 2) NOT NULL,
    PHARMID INT,
    FOREIGN KEY (PHARMID) REFERENCES PHARMACY(PHARMID)
);

CREATE TABLE PRESCRIPTION (
    PRESCRIPTIONID INT AUTO_INCREMENT PRIMARY KEY,
    CUSTOMID INT,
    MEDICINEID INT,
    FOREIGN KEY (CUSTOMID) REFERENCES CUSTOMER(CUSTOMID),
    FOREIGN KEY (MEDICINEID) REFERENCES MEDICINE_INVENTORY(MEDICINEID)
);

DROP DATABASE IF EXISTS WEB_DOCTORS;

CREATE DATABASE WEB_DOCTORS;

USE WEB_DOCTORS;

CREATE TABLE PHARMACY (
    PHARMID INT AUTO_INCREMENT PRIMARY KEY,
    PHARMNAME VARCHAR(50) NOT NULL,
    PHARMINVENTORY INT NOT NULL
);

CREATE TABLE CUSTOMER (
    CUSTOMID INT AUTO_INCREMENT PRIMARY KEY,
    CUSTOMNAME VARCHAR(50) NOT NULL
);

CREATE TABLE MEDICINE_INVENTORY (
    MEDICINEID INT AUTO_INCREMENT PRIMARY KEY,
    AMOUNT DECIMAL(13, 2) NOT NULL,
    PHARMID INT,
    FOREIGN KEY (PHARMID) REFERENCES PHARMACY(PHARMID)
);

CREATE TABLE PRESCRIPTION (
    PRESCRIPTIONID INT AUTO_INCREMENT PRIMARY KEY,
    CUSTOMID INT,
    MEDICINEID INT,
    FOREIGN KEY (CUSTOMID) REFERENCES CUSTOMER(CUSTOMID),
    FOREIGN KEY (MEDICINEID) REFERENCES MEDICINE_INVENTORY(MEDICINEID)
);